export const buildInterviewReportPrompt = ({
  resumeTxt,
  selfDescription,
  jobDescription,
}) => `
  Generate an interview report for a candidate with the following details:
  Resume: ${resumeTxt}
  Self Description: ${selfDescription}
  Job Description: ${jobDescription}
`;

export const buildResumePdfPrompt = ({
  resumeTxt,
  selfDescription,
  jobDescription,
}) => `
Generate resume for a candidate with the following details:
  Resume: ${resumeTxt}
  Self Description: ${selfDescription}
  Job Description: ${jobDescription}

  the response should be a JSON object with a single field "resumePdfHtml" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
  The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
  The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
  you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
  The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
  The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
`;

export const buildSkillQuizPrompt = ({ skill, level }) => `
  Create a skill assessment quiz for the skill: ${skill}
  Difficulty level: ${level}

  Requirements:
  - Generate exactly 20 multiple-choice questions.
  - Each question must be unique and relevant to ${skill} at ${level} level.
  - Use 4 options per question with one correct answer.
  - Include a short topic label for the concept being tested.
  - Include a brief explanation for why the correct answer is right.
  - Make the questions realistic for technical interview preparation.

  Return a valid JSON object with this exact structure:
  {
    "questions": [
      {
        "question": "...",
        "options": ["...", "...", "...", "..."],
        "correctIndex": 0,
        "topic": "...",
        "explanation": "..."
      }
    ]
  }

  Ensure the JSON is valid and parseable without markdown fences.
`;
